# Generated by Django 4.1.4 on 2022-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('alamat', models.CharField(max_length=100)),
                ('prodi', models.CharField(max_length=40)),
                ('kelas', models.CharField(max_length=40)),
            ],
        ),
    ]
